import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// Sample data for seeding
const sampleUsers = [
  { name: 'Jordan Vera', email: 'vera.jojo96@gmail.com', password: '123123' },
  { name: 'John Doe', email: 'john.doe@example.com', password: '123123' },
  { name: 'Jane Smith', email: 'jane.smith@example.com', password: '123123' },
  {
    name: 'Mike Johnson',
    email: 'mike.johnson@example.com',
    password: '123123',
  },
  {
    name: 'Sarah Wilson',
    email: 'sarah.wilson@example.com',
    password: '123123',
  },
  { name: 'David Brown', email: 'david.brown@example.com', password: '123123' },
  { name: 'Emily Davis', email: 'emily.davis@example.com', password: '123123' },
  {
    name: 'Chris Miller',
    email: 'chris.miller@example.com',
    password: '123123',
  },
  { name: 'Lisa Garcia', email: 'lisa.garcia@example.com', password: '123123' },
  {
    name: 'Tom Anderson',
    email: 'tom.anderson@example.com',
    password: '123123',
  },
  { name: 'Amy Taylor', email: 'amy.taylor@example.com', password: '123123' },
];

const sampleEvents = [
  {
    title: 'Tech Conference 2024',
    shortSummary: 'Annual tech conference with latest innovations',
    description:
      'Annual technology conference featuring the latest innovations in software development, AI, and cloud computing. Join industry leaders for keynotes, workshops, and networking.',
    startDate: new Date('2024-06-15T09:00:00Z'),
    endDate: new Date('2024-06-17T17:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'San Francisco Convention Center',
    venueName: 'Moscone Center',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
      'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Music Festival Summer',
    shortSummary: 'Three-day outdoor music festival',
    description:
      'Three-day outdoor music festival featuring indie, rock, and electronic artists. Experience amazing performances under the stars.',
    startDate: new Date('2024-07-20T14:00:00Z'),
    endDate: new Date('2024-07-22T23:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: true,
    location: 'Central Park, New York',
    venueName: 'Central Park Great Lawn',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
      'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'React Workshop',
    shortSummary: 'Hands-on React development workshop',
    description:
      'Hands-on workshop covering advanced React patterns, hooks, and performance optimization. Perfect for developers looking to level up their React skills.',
    startDate: new Date('2024-05-10T10:00:00Z'),
    endDate: new Date('2024-05-10T16:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Tech Hub Downtown',
    venueName: 'Innovation Lab',
    guestlistEnabled: false,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=Ke90Tje7VS0',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=500&fit=crop',
    imageGalleryEnabled: false,
    imageGalleryUrls: null,
    showOnExplore: true,
    isPasswordProtected: true,
    eventPassword: 'react2024',
  },
  {
    title: 'Startup Meetup',
    shortSummary: 'Networking for entrepreneurs and investors',
    description:
      'Networking event for entrepreneurs, investors, and startup enthusiasts. Connect with like-minded individuals and potential collaborators.',
    startDate: new Date('2024-04-25T18:00:00Z'),
    endDate: new Date('2024-04-25T21:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: true,
    location: 'WeWork Office',
    venueName: 'WeWork Innovation Space',
    guestlistEnabled: true,
    eventFeaturesEnabled: false,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=500&fit=crop',
    imageGalleryEnabled: false,
    imageGalleryUrls: null,
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Data Science Seminar',
    shortSummary: 'Expert-led ML and data analysis seminar',
    description:
      'Expert-led seminar on machine learning, data visualization, and statistical analysis. Learn from industry professionals.',
    startDate: new Date('2024-08-05T13:00:00Z'),
    endDate: new Date('2024-08-05T17:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'University Campus',
    venueName: 'Computer Science Building',
    guestlistEnabled: false,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=aircAruvnKk',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Design Thinking Workshop',
    shortSummary: 'Interactive UX design workshop',
    description:
      'Interactive workshop on user-centered design methodologies and prototyping. Perfect for designers and product managers.',
    startDate: new Date('2024-06-30T09:30:00Z'),
    endDate: new Date('2024-06-30T15:30:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Design Studio',
    venueName: 'Creative Hub',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
      'https://images.unsplash.com/photo-1559028012-481c04fa702d?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Blockchain Conference',
    shortSummary: 'Exploring Web3 and DeFi applications',
    description:
      'Exploring the future of blockchain technology, DeFi, and Web3 applications. Join crypto enthusiasts and developers.',
    startDate: new Date('2024-09-12T08:00:00Z'),
    endDate: new Date('2024-09-13T18:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Crypto Convention Center',
    venueName: 'Blockchain Hub',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=SSo_EIwHSd4',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800',
      'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Mobile App Development',
    shortSummary: 'Cross-platform mobile app course',
    description:
      'Comprehensive course on building cross-platform mobile applications. Learn React Native, Flutter, and native development.',
    startDate: new Date('2024-05-20T10:00:00Z'),
    endDate: new Date('2024-05-22T16:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Tech Academy',
    venueName: 'Mobile Development Lab',
    guestlistEnabled: false,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=0-S5a0eXPoc',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=500&fit=crop',
    imageGalleryEnabled: false,
    imageGalleryUrls: null,
    showOnExplore: true,
    isPasswordProtected: true,
    eventPassword: 'mobile2024',
  },
  {
    title: 'DevOps Training',
    shortSummary: 'CI/CD and cloud deployment training',
    description:
      'Learn CI/CD pipelines, containerization, and cloud deployment strategies. Hands-on training for DevOps engineers.',
    startDate: new Date('2024-07-08T09:00:00Z'),
    endDate: new Date('2024-07-10T17:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Cloud Computing Center',
    venueName: 'DevOps Lab',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Product Management Summit',
    shortSummary: 'Industry leaders on product strategy',
    description:
      'Industry leaders discussing product strategy, user research, and market analysis. Essential for product managers.',
    startDate: new Date('2024-08-20T08:30:00Z'),
    endDate: new Date('2024-08-21T17:30:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Business Center',
    venueName: 'Executive Conference Room',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=huqFd7O2238',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800',
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'AI & Machine Learning Summit',
    shortSummary: 'Cutting-edge AI research and applications',
    description:
      'Explore the latest developments in artificial intelligence, machine learning, and deep learning. Featuring keynote speakers from leading tech companies and research institutions.',
    startDate: new Date('2024-10-15T08:00:00Z'),
    endDate: new Date('2024-10-16T18:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Silicon Valley Convention Center',
    venueName: 'AI Innovation Hub',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=aircAruvnKk',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Cooking Masterclass',
    shortSummary: 'Learn from Michelin-starred chefs',
    description:
      'Hands-on cooking experience with world-renowned chefs. Learn advanced techniques, plating, and flavor combinations in an intimate setting.',
    startDate: new Date('2024-11-05T10:00:00Z'),
    endDate: new Date('2024-11-05T16:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: true,
    location: 'Culinary Institute',
    venueName: 'Professional Kitchen Studio',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Photography Workshop',
    shortSummary: 'Street photography and composition techniques',
    description:
      'Master the art of street photography with professional photographers. Learn composition, lighting, and storytelling through images.',
    startDate: new Date('2024-12-08T09:00:00Z'),
    endDate: new Date('2024-12-08T17:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Downtown Arts District',
    venueName: 'Creative Photography Studio',
    guestlistEnabled: false,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=Ke90Tje7VS0',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Fitness Bootcamp',
    shortSummary: 'High-intensity interval training session',
    description:
      'Join our intensive fitness bootcamp designed to push your limits. Led by certified trainers with personalized workout plans.',
    startDate: new Date('2024-09-28T06:00:00Z'),
    endDate: new Date('2024-09-28T08:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: true,
    location: 'Central Park',
    venueName: 'Outdoor Fitness Area',
    guestlistEnabled: true,
    eventFeaturesEnabled: false,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=500&fit=crop',
    imageGalleryEnabled: false,
    imageGalleryUrls: null,
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Wine Tasting Experience',
    shortSummary: 'Premium wines from around the world',
    description:
      'Discover exceptional wines from renowned vineyards. Expert sommelier will guide you through tastings and food pairings.',
    startDate: new Date('2024-10-30T19:00:00Z'),
    endDate: new Date('2024-10-30T22:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Wine Cellar Downtown',
    venueName: 'Elegant Tasting Room',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800',
      'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: true,
    eventPassword: 'wine2024',
  },
  {
    title: 'Cybersecurity Conference',
    shortSummary: 'Latest trends in digital security',
    description:
      'Stay ahead of cyber threats with insights from security experts. Covering threat intelligence, incident response, and emerging technologies.',
    startDate: new Date('2024-11-18T09:00:00Z'),
    endDate: new Date('2024-11-19T17:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Security Convention Center',
    venueName: 'Cyber Defense Hall',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=SSo_EIwHSd4',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Art Gallery Opening',
    shortSummary: 'Contemporary art exhibition launch',
    description:
      'Celebrate the opening of our latest contemporary art exhibition featuring emerging and established artists from around the world.',
    startDate: new Date('2024-12-15T18:00:00Z'),
    endDate: new Date('2024-12-15T21:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Modern Art Gallery',
    venueName: 'Contemporary Exhibition Space',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Language Exchange Meetup',
    shortSummary: 'Practice foreign languages with native speakers',
    description:
      'Connect with language learners and native speakers for conversation practice. Multiple languages supported including Spanish, French, German, and Japanese.',
    startDate: new Date('2024-11-12T19:30:00Z'),
    endDate: new Date('2024-11-12T21:30:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: true,
    location: 'Community Center',
    venueName: 'Language Learning Lounge',
    guestlistEnabled: true,
    eventFeaturesEnabled: false,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=500&fit=crop',
    imageGalleryEnabled: false,
    imageGalleryUrls: null,
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Virtual Reality Gaming Tournament',
    shortSummary: 'Competitive VR gaming championship',
    description:
      'Join the ultimate VR gaming tournament featuring the latest virtual reality games. Compete for prizes and glory in immersive environments.',
    startDate: new Date('2024-10-25T10:00:00Z'),
    endDate: new Date('2024-10-25T18:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'VR Gaming Arena',
    venueName: 'Virtual Reality Center',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=0-S5a0eXPoc',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1592478411213-6153e4c4c8f4?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1592478411213-6153e4c4c8f4?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Sustainable Living Workshop',
    shortSummary: 'Learn eco-friendly lifestyle practices',
    description:
      'Discover practical ways to reduce your environmental footprint. Topics include zero-waste living, renewable energy, and sustainable consumption.',
    startDate: new Date('2024-11-25T14:00:00Z'),
    endDate: new Date('2024-11-25T17:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Environmental Center',
    venueName: 'Green Living Lab',
    guestlistEnabled: false,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Comedy Night',
    shortSummary: 'Stand-up comedy showcase',
    description:
      'Laugh the night away with talented comedians from the local scene. Featuring both established performers and up-and-coming talent.',
    startDate: new Date('2024-12-20T20:00:00Z'),
    endDate: new Date('2024-12-20T23:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: true,
    location: 'Comedy Club Downtown',
    venueName: 'Laugh Track Theater',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Investment Strategies Seminar',
    shortSummary: 'Financial planning and investment insights',
    description:
      'Learn from financial experts about portfolio diversification, risk management, and long-term wealth building strategies.',
    startDate: new Date('2024-11-08T13:00:00Z'),
    endDate: new Date('2024-11-08T16:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Financial District',
    venueName: 'Investment Advisory Center',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=huqFd7O2238',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=500&fit=crop',
    imageGalleryEnabled: false,
    imageGalleryUrls: null,
    showOnExplore: true,
    isPasswordProtected: true,
    eventPassword: 'invest2024',
  },
  {
    title: 'Yoga Retreat',
    shortSummary: 'Weekend wellness and mindfulness',
    description:
      'Escape the city for a rejuvenating yoga retreat. Practice meditation, enjoy healthy meals, and connect with nature in a peaceful setting.',
    startDate: new Date('2024-12-01T08:00:00Z'),
    endDate: new Date('2024-12-03T17:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Mountain Retreat Center',
    venueName: 'Serenity Wellness Lodge',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Board Game Night',
    shortSummary: 'Strategic board games and social fun',
    description:
      'Join fellow board game enthusiasts for an evening of strategy, fun, and friendly competition. Games range from classic to modern favorites.',
    startDate: new Date('2024-11-15T18:00:00Z'),
    endDate: new Date('2024-11-15T22:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: true,
    location: 'Game Cafe',
    venueName: 'Board Game Lounge',
    guestlistEnabled: true,
    eventFeaturesEnabled: false,
    youtubeVideoEnabled: false,
    youtubeVideoUrl: null,
    flyerImageUrl:
      'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400&h=500&fit=crop',
    imageGalleryEnabled: false,
    imageGalleryUrls: null,
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
  {
    title: 'Digital Marketing Bootcamp',
    shortSummary: 'Master social media and online advertising',
    description:
      'Comprehensive digital marketing course covering SEO, social media strategy, content marketing, and paid advertising campaigns.',
    startDate: new Date('2024-12-10T09:00:00Z'),
    endDate: new Date('2024-12-12T17:00:00Z'),
    timezone: 'GMT -5',
    isRecurringSeries: false,
    location: 'Marketing Academy',
    venueName: 'Digital Strategy Lab',
    guestlistEnabled: true,
    eventFeaturesEnabled: true,
    youtubeVideoEnabled: true,
    youtubeVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    flyerImageUrl:
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=500&fit=crop',
    imageGalleryEnabled: true,
    imageGalleryUrls: JSON.stringify([
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    ]),
    showOnExplore: true,
    isPasswordProtected: false,
    eventPassword: null,
  },
];

// Sample tickets for events
const sampleTickets = [
  // Tech Conference 2024 tickets
  {
    eventIndex: 0, // Tech Conference 2024
    name: 'Early Bird',
    description: 'Early bird pricing for tech enthusiasts',
    grossPrice: 299.99,
    displayPrice: '$299.99',
    quantity: 100,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-03-31T23:59:59Z'),
    limitTicketValidity: false,
    validityStartDate: null,
    validityEndDate: null,
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 5,
  },
  {
    eventIndex: 0,
    name: 'Regular Admission',
    description: 'Standard conference admission',
    grossPrice: 399.99,
    displayPrice: '$399.99',
    quantity: 500,
    isUnlimited: false,
    limitSalesPeriod: false,
    salesStartDate: null,
    salesEndDate: null,
    limitTicketValidity: false,
    validityStartDate: null,
    validityEndDate: null,
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 10,
  },
  {
    eventIndex: 0,
    name: 'VIP Pass',
    description: 'VIP access with premium amenities',
    grossPrice: 799.99,
    displayPrice: '$799.99',
    quantity: 50,
    isUnlimited: false,
    limitSalesPeriod: false,
    salesStartDate: null,
    salesEndDate: null,
    limitTicketValidity: false,
    validityStartDate: null,
    validityEndDate: null,
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 2,
  },

  // Music Festival Summer tickets
  {
    eventIndex: 1,
    name: 'General Admission',
    description: 'Access to all festival areas',
    grossPrice: 149.99,
    displayPrice: '$149.99',
    quantity: 2000,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-02-01T00:00:00Z'),
    salesEndDate: new Date('2024-07-15T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-07-20T14:00:00Z'),
    validityEndDate: new Date('2024-07-22T23:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 8,
  },
  {
    eventIndex: 1,
    name: 'VIP Experience',
    description: 'Premium viewing areas and amenities',
    grossPrice: 299.99,
    displayPrice: '$299.99',
    quantity: 200,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-02-01T00:00:00Z'),
    salesEndDate: new Date('2024-07-15T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-07-20T14:00:00Z'),
    validityEndDate: new Date('2024-07-22T23:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 4,
  },

  // React Workshop tickets
  {
    eventIndex: 2,
    name: 'Workshop Access',
    description: 'Full day React workshop with materials',
    grossPrice: 199.99,
    displayPrice: '$199.99',
    quantity: 30,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-15T00:00:00Z'),
    salesEndDate: new Date('2024-05-05T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-05-10T10:00:00Z'),
    validityEndDate: new Date('2024-05-10T16:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },

  // Startup Meetup tickets
  {
    eventIndex: 3,
    name: 'Free Admission',
    description: 'Complimentary networking event',
    grossPrice: 0,
    displayPrice: 'Free',
    quantity: null,
    isUnlimited: true,
    limitSalesPeriod: false,
    salesStartDate: null,
    salesEndDate: null,
    limitTicketValidity: false,
    validityStartDate: null,
    validityEndDate: null,
    limitPurchaseQuantity: false,
    minPurchaseQuantity: null,
    maxPurchaseQuantity: null,
  },

  // Data Science Seminar tickets
  {
    eventIndex: 4,
    name: 'Student Rate',
    description: 'Discounted rate for students',
    grossPrice: 49.99,
    displayPrice: '$49.99',
    quantity: 50,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-08-01T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-08-05T13:00:00Z'),
    validityEndDate: new Date('2024-08-05T17:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },
  {
    eventIndex: 4,
    name: 'Professional Rate',
    description: 'Standard rate for professionals',
    grossPrice: 99.99,
    displayPrice: '$99.99',
    quantity: 100,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-08-01T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-08-05T13:00:00Z'),
    validityEndDate: new Date('2024-08-05T17:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 3,
  },

  // Design Thinking Workshop tickets
  {
    eventIndex: 5,
    name: 'Workshop Pass',
    description: 'Interactive design workshop access',
    grossPrice: 179.99,
    displayPrice: '$179.99',
    quantity: 25,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-02-01T00:00:00Z'),
    salesEndDate: new Date('2024-06-25T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-06-30T09:30:00Z'),
    validityEndDate: new Date('2024-06-30T15:30:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 2,
  },

  // Blockchain Conference tickets
  {
    eventIndex: 6,
    name: 'Conference Pass',
    description: 'Two-day blockchain conference access',
    grossPrice: 499.99,
    displayPrice: '$499.99',
    quantity: 300,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-09-10T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-09-12T08:00:00Z'),
    validityEndDate: new Date('2024-09-13T18:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 5,
  },
  {
    eventIndex: 6,
    name: 'Developer Track',
    description: 'Technical sessions for developers',
    grossPrice: 399.99,
    displayPrice: '$399.99',
    quantity: 150,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-09-10T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-09-12T08:00:00Z'),
    validityEndDate: new Date('2024-09-13T18:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 3,
  },

  // Mobile App Development tickets
  {
    eventIndex: 7,
    name: 'Course Access',
    description: 'Three-day mobile development course',
    grossPrice: 899.99,
    displayPrice: '$899.99',
    quantity: 20,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-05-15T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-05-20T10:00:00Z'),
    validityEndDate: new Date('2024-05-22T16:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },

  // DevOps Training tickets
  {
    eventIndex: 8,
    name: 'Training Pass',
    description: 'Three-day DevOps training program',
    grossPrice: 1299.99,
    displayPrice: '$1,299.99',
    quantity: 15,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-07-01T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-07-08T09:00:00Z'),
    validityEndDate: new Date('2024-07-10T17:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },

  // Product Management Summit tickets
  {
    eventIndex: 9,
    name: 'Summit Pass',
    description: 'Two-day product management summit',
    grossPrice: 699.99,
    displayPrice: '$699.99',
    quantity: 200,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-08-15T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-08-20T08:30:00Z'),
    validityEndDate: new Date('2024-08-21T17:30:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 3,
  },
  {
    eventIndex: 9,
    name: 'Executive Pass',
    description: 'Premium access with exclusive sessions',
    grossPrice: 1299.99,
    displayPrice: '$1,299.99',
    quantity: 50,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-08-15T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-08-20T08:30:00Z'),
    validityEndDate: new Date('2024-08-21T17:30:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 2,
  },

  // AI & Machine Learning Summit tickets (Event Index 10)
  {
    eventIndex: 10,
    name: 'Student Pass',
    description: 'Discounted rate for students and researchers',
    grossPrice: 199.99,
    displayPrice: '$199.99',
    quantity: 100,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-10-10T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-10-15T08:00:00Z'),
    validityEndDate: new Date('2024-10-16T18:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 2,
  },
  {
    eventIndex: 10,
    name: 'Professional Pass',
    description: 'Full access to AI summit sessions',
    grossPrice: 599.99,
    displayPrice: '$599.99',
    quantity: 300,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-10-10T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-10-15T08:00:00Z'),
    validityEndDate: new Date('2024-10-16T18:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 5,
  },
  {
    eventIndex: 10,
    name: 'VIP Access',
    description: 'Premium access with networking dinner',
    grossPrice: 999.99,
    displayPrice: '$999.99',
    quantity: 50,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-10-10T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-10-15T08:00:00Z'),
    validityEndDate: new Date('2024-10-16T18:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 2,
  },

  // Cooking Masterclass tickets (Event Index 11)
  {
    eventIndex: 11,
    name: 'Masterclass Access',
    description: 'Full day cooking experience with materials',
    grossPrice: 299.99,
    displayPrice: '$299.99',
    quantity: 20,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-10-30T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-11-05T10:00:00Z'),
    validityEndDate: new Date('2024-11-05T16:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 2,
  },

  // Photography Workshop tickets (Event Index 12)
  {
    eventIndex: 12,
    name: 'Workshop Pass',
    description: 'Full day photography workshop with equipment',
    grossPrice: 149.99,
    displayPrice: '$149.99',
    quantity: 15,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-12-01T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-12-08T09:00:00Z'),
    validityEndDate: new Date('2024-12-08T17:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },

  // Fitness Bootcamp tickets (Event Index 13)
  {
    eventIndex: 13,
    name: 'Bootcamp Session',
    description: 'High-intensity fitness session',
    grossPrice: 25.99,
    displayPrice: '$25.99',
    quantity: null,
    isUnlimited: true,
    limitSalesPeriod: false,
    salesStartDate: null,
    salesEndDate: null,
    limitTicketValidity: true,
    validityStartDate: new Date('2024-09-28T06:00:00Z'),
    validityEndDate: new Date('2024-09-28T08:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },

  // Wine Tasting Experience tickets (Event Index 14)
  {
    eventIndex: 14,
    name: 'Tasting Experience',
    description: 'Premium wine tasting with expert guidance',
    grossPrice: 89.99,
    displayPrice: '$89.99',
    quantity: 30,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-10-25T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-10-30T19:00:00Z'),
    validityEndDate: new Date('2024-10-30T22:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 4,
  },

  // Cybersecurity Conference tickets (Event Index 15)
  {
    eventIndex: 15,
    name: 'Conference Pass',
    description: 'Two-day cybersecurity conference access',
    grossPrice: 449.99,
    displayPrice: '$449.99',
    quantity: 200,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-11-15T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-11-18T09:00:00Z'),
    validityEndDate: new Date('2024-11-19T17:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 3,
  },
  {
    eventIndex: 15,
    name: 'Security Professional',
    description: 'Advanced sessions for security professionals',
    grossPrice: 349.99,
    displayPrice: '$349.99',
    quantity: 100,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-11-15T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-11-18T09:00:00Z'),
    validityEndDate: new Date('2024-11-19T17:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 2,
  },

  // Art Gallery Opening tickets (Event Index 16)
  {
    eventIndex: 16,
    name: 'Opening Night',
    description: 'Exclusive gallery opening with artist meet & greet',
    grossPrice: 49.99,
    displayPrice: '$49.99',
    quantity: 100,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-12-10T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-12-15T18:00:00Z'),
    validityEndDate: new Date('2024-12-15T21:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 4,
  },

  // Language Exchange Meetup tickets (Event Index 17)
  {
    eventIndex: 17,
    name: 'Language Exchange',
    description: 'Free language practice session',
    grossPrice: 0,
    displayPrice: 'Free',
    quantity: null,
    isUnlimited: true,
    limitSalesPeriod: false,
    salesStartDate: null,
    salesEndDate: null,
    limitTicketValidity: true,
    validityStartDate: new Date('2024-11-12T19:30:00Z'),
    validityEndDate: new Date('2024-11-12T21:30:00Z'),
    limitPurchaseQuantity: false,
    minPurchaseQuantity: null,
    maxPurchaseQuantity: null,
  },

  // Virtual Reality Gaming Tournament tickets (Event Index 18)
  {
    eventIndex: 18,
    name: 'Tournament Entry',
    description: 'VR gaming tournament participation',
    grossPrice: 79.99,
    displayPrice: '$79.99',
    quantity: 50,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-10-20T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-10-25T10:00:00Z'),
    validityEndDate: new Date('2024-10-25T18:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },
  {
    eventIndex: 18,
    name: 'Spectator Pass',
    description: 'Watch the tournament and enjoy VR demos',
    grossPrice: 29.99,
    displayPrice: '$29.99',
    quantity: 100,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-10-20T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-10-25T10:00:00Z'),
    validityEndDate: new Date('2024-10-25T18:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 3,
  },

  // Sustainable Living Workshop tickets (Event Index 19)
  {
    eventIndex: 19,
    name: 'Workshop Access',
    description: 'Sustainable living workshop with materials',
    grossPrice: 39.99,
    displayPrice: '$39.99',
    quantity: 40,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-11-20T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-11-25T14:00:00Z'),
    validityEndDate: new Date('2024-11-25T17:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 2,
  },

  // Comedy Night tickets (Event Index 20)
  {
    eventIndex: 20,
    name: 'Comedy Show',
    description: 'Stand-up comedy showcase',
    grossPrice: 19.99,
    displayPrice: '$19.99',
    quantity: 80,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-12-15T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-12-20T20:00:00Z'),
    validityEndDate: new Date('2024-12-20T23:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 6,
  },

  // Investment Strategies Seminar tickets (Event Index 21)
  {
    eventIndex: 21,
    name: 'Seminar Access',
    description: 'Financial planning seminar with materials',
    grossPrice: 199.99,
    displayPrice: '$199.99',
    quantity: 60,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-11-01T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-11-08T13:00:00Z'),
    validityEndDate: new Date('2024-11-08T16:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 2,
  },

  // Yoga Retreat tickets (Event Index 22)
  {
    eventIndex: 22,
    name: 'Retreat Package',
    description: 'Three-day yoga retreat with meals and accommodation',
    grossPrice: 599.99,
    displayPrice: '$599.99',
    quantity: 25,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-11-25T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-12-01T08:00:00Z'),
    validityEndDate: new Date('2024-12-03T17:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },

  // Board Game Night tickets (Event Index 23)
  {
    eventIndex: 23,
    name: 'Game Night',
    description: 'Board game evening with refreshments',
    grossPrice: 12.99,
    displayPrice: '$12.99',
    quantity: null,
    isUnlimited: true,
    limitSalesPeriod: false,
    salesStartDate: null,
    salesEndDate: null,
    limitTicketValidity: true,
    validityStartDate: new Date('2024-11-15T18:00:00Z'),
    validityEndDate: new Date('2024-11-15T22:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },

  // Digital Marketing Bootcamp tickets (Event Index 24)
  {
    eventIndex: 24,
    name: 'Bootcamp Access',
    description: 'Three-day digital marketing intensive',
    grossPrice: 799.99,
    displayPrice: '$799.99',
    quantity: 30,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-12-05T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-12-10T09:00:00Z'),
    validityEndDate: new Date('2024-12-12T17:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },
  {
    eventIndex: 24,
    name: 'Early Bird',
    description: 'Discounted early bird pricing',
    grossPrice: 599.99,
    displayPrice: '$599.99',
    quantity: 15,
    isUnlimited: false,
    limitSalesPeriod: true,
    salesStartDate: new Date('2024-01-01T00:00:00Z'),
    salesEndDate: new Date('2024-10-31T23:59:59Z'),
    limitTicketValidity: true,
    validityStartDate: new Date('2024-12-10T09:00:00Z'),
    validityEndDate: new Date('2024-12-12T17:00:00Z'),
    limitPurchaseQuantity: true,
    minPurchaseQuantity: 1,
    maxPurchaseQuantity: 1,
  },
];

async function main() {
  console.log('🌱 Starting database seeding...');

  // Clear existing data
  await prisma.ticket.deleteMany();
  await prisma.event.deleteMany();
  await prisma.user.deleteMany();
  console.log('🗑️  Cleared existing data');

  // Create users
  const users: any[] = [];
  for (const userData of sampleUsers) {
    // Hash the password before saving
    const hashedPassword = await bcrypt.hash(userData.password, 10);

    const user = await prisma.user.create({
      data: {
        ...userData,
        password: hashedPassword,
      },
    });
    users.push(user);
  }
  console.log(`👥 Created ${users.length} users`);

  // Create events
  const events: any[] = [];
  for (let i = 0; i < sampleEvents.length; i++) {
    const eventData = sampleEvents[i];
    const randomUser = users[Math.floor(Math.random() * users.length)];

    const event = await prisma.event.create({
      data: {
        ...eventData,
        userId: randomUser.id,
      },
    });
    events.push(event);
  }
  console.log(`🎉 Created ${events.length} events`);

  // Create tickets
  const tickets: any[] = [];
  for (const ticketData of sampleTickets) {
    const event = events[ticketData.eventIndex];
    const { eventIndex, ...ticketFields } = ticketData;

    const ticket = await prisma.ticket.create({
      data: {
        ...ticketFields,
        eventId: event.id,
      },
    });
    tickets.push(ticket);
  }
  console.log(`🎫 Created ${tickets.length} tickets`);

  console.log('✅ Database seeding completed!');
  console.log(`📊 Total users: ${users.length}`);
  console.log(`📊 Total events: ${events.length}`);
  console.log(`📊 Total tickets: ${tickets.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
